app/users/models.py
from app import db
from app.users import constants as CONST 

class User(db.Model):

    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(20))
    gender = db.Column(db.String(10))
    role = db.Column(db.SmallInteger, default=CONST.USER)
    status = db.Column(db.SmallInteger, default=CONST.NEW)

    def __init__(self, name=None, email=None, password=None, gender=None):
      self.name = name
      self.email = email
      self.password = password
      self.gender = gender 

    def getStatus(self):
      return CONST.STATUS[self.status]

    def getRole(self):
      return CONST.ROLE[self.role]

    def __repr__(self):
        return '<User %r>' % (self.name)

app/users/forms.py
from flask.ext.wtf import Form, SelectField, TextField, PasswordField, BooleanField, RecaptchaField
from flask.ext.wtf import Required, Email, EqualTo

class LoginForm(Form):
  email = TextField('Email', [Required(), Email()])
  password = PasswordField('Password', [Required()])

class RegisterForm(Form):
  name = TextField('Name', [Required()])
  email = TextField('Email', [Required(), Email()])
  password = PasswordField('Password', [Required()])
  confirm = PasswordField('Confirm Password', [
      Required(),
      EqualTo('password', message='Passwords must match')
      ])
  accept_tos = BooleanField('I accept the TOS', [Required()])
  gender = SelectField('Gender',choices = [('gender','Gender'),('male','Male'),('female','Female'),('other','Other'),('private','Private')] )
  recaptcha = RecaptchaField()

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash

from app import db
from app.users.forms import RegisterForm, LoginForm
from app.users.models import User
from app.users.decorators import requires_login

mod = Blueprint('users', __name__, url_prefix='/users')


@mod.route('/me/')
@requires_login
def home():
  return render_template("users/profile.html", user=g.user)

   
@mod.route('/login/', methods=['GET', 'POST'])
def login():
  """
  Login form
  """
  form = LoginForm(request.form)
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and check_password_hash(user.password, form.password.data):
      session['user_id'] = user.id
      flash('Welcome %s' % user.name)
      return redirect(url_for('feed.home'))
    flash('Wrong email or password', 'error-message')
  return render_template("users/login.html", form=form)


@mod.route('/register/', methods=['GET', 'POST'])
def register():
  """
  Registration Form
  """
  form = RegisterForm(request.form)
  if form.validate_on_submit():
    user = User(form.name.data, form.email.data, \
      generate_password_hash(form.password.data),form.gender.data)
    db.session.add(user)
    db.session.commit()

    session['user_id'] = user.id

    flash('Thanks for registering')
    return redirect(url_for('feed.home'))
  return render_template("users/register.html", form=form)


@mod.route('/logout/')
def logout():
  session.pop('user_id', None)
  flash('You were logged out')
  return redirect(url_for('users.login'))

app/templates/users/login.html
{% extends "base.html" %}
{% block content %}
  {% from "forms/macros.html" import render_field %}
  <form class="form-horizontal" method="POST" action="." class="form">
    <fieldset>
      <br>
      <br>
      {{ form.csrf_token }}
      {{ render_field(form.email, class="input-xlarge") }}
      {{ render_field(form.password, class="input-xlarge") }}
      <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
          <button type=submit class="btn btn-inverse">Login</button>
        </div>
      </div>
    </fieldset>
  </form>
{% endblock %}

{% block metanav%}
  <a href="{{ url_for('users.register') }}">Register</a>
{% endblock %}

app/templates/users/profile.html
<!doctype html>
{% extends "base.html" %}

{% block metanav %}
  <a href="{{ url_for('feed.home') }}">Feed Home</a>
  &nbsp; 
  <a href="{{ url_for('users.logout') }}">Logout</a>
{% endblock %}


{% block content %}
<table class="table table-hover">
  <tr>
    <td>Name</td>
    <td>{{user.name}}</td>
  </tr>
  <tr class="success">
    <td>Email</td>
    <td>{{user.email}}</td>
  </tr>
  <tr class="warning">
    <td>Password</td>
    <td>******</td>
  </tr>
  <tr>
    <td>Gender</td>
    <td>{{user.gender}}</td>
  </tr>
  <tr>
    <td>Role</td>
    <td>{{user.getRole()}}</td>
  </tr>
  <tr>
    <td>Status</td>
    <td>{{user.getStatus()}}</td>
  </tr>
</table>


{% endblock %}

app/templates/users/register.html
{% extends "base.html" %}
{% block content %}
  {% from "forms/macros.html" import render_field %}
  <form class="form-horizontal" method="POST" action="." class="form">
    <fieldset>
      <legend>Registration</legend>
      <br>
      <br>
      {{ form.csrf_token }}
      {{ render_field(form.name, class="input-xlarge") }}
      {{ render_field(form.email, class="input-xlarge") }}
      {{ render_field(form.password, class="input-xlarge") }}
      {{ render_field(form.confirm, class="input-xlarge") }}
      {{ render_field(form.gender) }}
      <div class = "in_line">
        {{ render_field(form.accept_tos, class="input checkbox") }}
      </div>
      <div class = "recaptcha">
        {{ form.recaptcha }}
      </div>
      <br>
      <br>
      <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
          <button id = "register_button" type=submit class="btn btn-success">Register My Account</button>
        </div>
      </div>
   </fieldset>
  </form>
{% endblock %}

{% block metanav%}
  <a href="{{ url_for('users.login') }}">Login</a>
{% endblock %}