app/feed/models.py
from app import db

class Feed(db.Model):

    __tablename__ = 'feed'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    link = db.Column(db.String(200))

    def __init__(self, name=None, link=None):
      self.name = name 
      self.link = link 

    def getId(self):
      return self.id

    def getLink(self):
      return self.link

    def getName(self):
      return self.name

    def __repr__(self):
        return '<Feed %r>' % (self.name)


class FeedUser(db.Model):

    __tablename__ = 'feeduser'
    id = db.Column(db.Integer, primary_key=True)
    fid = db.Column(db.Integer, db.ForeignKey('feed.id'))
    uid = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __init__(self, fid=None, uid=None):
      self.fid = fid 
      self.uid = uid

    def getFeed(self):
      return self.fid

    def getUser(self):
      return self.uid

    def __repr__(self):
        return '<FeedUser %r>' % (self.id)


class Star(db.Model):

    __tablename__ = 'star'
    id = db.Column(db.Integer, primary_key=True)
    uid = db.Column(db.Integer, db.ForeignKey('user.id'))
    fid = db.Column(db.Integer, db.ForeignKey('feed.id'))
    entryid = db.Column(db.String(200))

    def __init__(self, uid=None, fid=None, entryid=None):
      self.uid = uid
      self.fid = fid 
      self.entryid = entryid

    def getUser(self):
      return self.uid

    def getFeed(self):
      return self.fid

    def getEntryId(self):
      return self.entryid

    def __repr__(self):
        return '<Star %r>' % (self.id)

app/feed/forms.py
from flask.ext.wtf import Form, TextField, HiddenField
from flask.ext.wtf import Required, EqualTo

class RegisterForm(Form):
  link = TextField('RSS link', [Required()])


class DeleteForm(Form):
  feedName = HiddenField('FeedName', [Required()])

app/feed/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for

from app import db
from app.feed.forms import RegisterForm, DeleteForm
from app.rss_reader.parser import RSSParser
from app.users.models import User
from app.feed.models import Feed, FeedUser, Star
from app.users.decorators import requires_login
import collections

mod = Blueprint('feed', __name__, url_prefix='/feed')

@requires_login
@mod.route('/explore/', methods=['GET', 'POST'])
def explore():
  """
  Find all starred by other people
  """
  exploreEntries = findExplore()
  ranking_order = r_order(exploreEntries)
  form = RegisterForm(request.form)
  if form.validate_on_submit():
    insertFeed(form.link.data)
  return render_template("feed/explore.html", form=form, exploreEntries = exploreEntries, ranking_order = ranking_order )

@requires_login
@mod.route('/starred/', methods=['GET', 'POST'])
def starred():
  """
  starred entry list
  """
  actionTable = {'add':True, 'del':False}

  feedLink = request.args.get('feedLink',None)
  entryId = request.args.get('entryId',None)
  action = request.args.get('action',None)
  # Action = True: insert, Action = False : delete
  if not (action is None):
    insertStar(feedLink, entryId, actionTable.get(action))

  starredEntries = findStarred(g.user.id)
  form = RegisterForm(request.form)
  if form.validate_on_submit():
    insertFeed(form.link.data)
  return render_template("feed/starred.html", form=form, starredEntries = starredEntries)


@requires_login
@mod.route('/star/', methods=['GET', 'POST'])
def star():
  """
  Store the starred entryId of a feed
  """

  actionTable = {'add':True, 'del':False}

  feedLink = request.args.get('feedLink',None)
  entryId = request.args.get('entryId',None)
  action = request.args.get('action',None)
  # Action = True: insert, Action = False : delete
  insertStar(feedLink, entryId, actionTable[action])
  entriesAry = createEntriesAry(feedLink)
  starredAry = createStarredAry(feedLink)

  form = RegisterForm(request.form)
  if form.validate_on_submit():
    insertFeed(form.link.data)
  return render_template("feed/detail.html", form=form, entriesAry=entriesAry, starredAry = starredAry)


@requires_login
@mod.route('/detail/<feedName>', methods=['GET', 'POST'])
def detail(feedName = None):
  """
  Display the RSS Reader Detail
  """
  link = request.args.get('feedLink',None)
  entriesAry = createEntriesAry(link)
  starredAry = createStarredAry(link)
  form = RegisterForm(request.form)
  if form.validate_on_submit():
    insertFeed(form.link.data)
  return render_template("feed/detail.html", form=form, entriesAry=entriesAry, starredAry = starredAry)


#@requires_login
@mod.route('/home/', methods=['GET', 'POST'])
def home():
  """
  Display the RSS Reader Home
  """
  rform = RegisterForm(request.form)
  dform = DeleteForm(request.form)

  # Unsubcribe a RSS link
  if dform.validate_on_submit():
    deleteFeed(dform.feedName.data)

  # Subcribe a RSS link
  if rform.validate_on_submit():
    insertFeed(rform.link.data)
  g.feeds = createFeedList(g.user.id)
  return render_template("feed/home.html", rform = rform, dform = dform ,feeds = g.feeds)


def insertFeed(link):
  """
  Insert feed into DB
  """
  rssParser = RSSParser(link)
  feed = Feed(rssParser.getName(), link)
  db.session.add(feed)
  db.session.commit()
  justAdd = Feed.query.filter_by(link=link).first()
  feeduser = FeedUser(justAdd.getId(), g.user.id)
  db.session.add(feeduser)
  db.session.commit()


def createFeedList(uid):
  """
  Query feeds from DB
  Use RSSParser to get detail and show
  """
  rel = {}
  fu_ary = FeedUser.query.filter_by(uid=uid).all()
  if fu_ary:
    for relation in fu_ary:
      fl = Feed.query.filter_by(id=relation.fid).first()
      rel[fl.name] = createHeadline(fl.link)
  return rel

def createHeadline(link):
  """
  Use RSSParser to get HeadLine
  """
  rel={}
  rssParser = RSSParser(link)
  # Save summary
  for entry in rssParser.getDTO().entries:
    f = open('app/templates/tmp/sum_'+entry.id[7:].replace('/','_'),'w')
    summary = entry.summary.encode('utf-8')
    f.write(summary)
    f.close()

  rel["number"] = rssParser.getNumber()
  rel["href"] = rssParser.getHref()
  rel["head"] = rssParser.getHead()
  rel["entryLink"] = rssParser.getEntryLink()
  rel["link"] = link
  return rel

def createEntriesAry(link):
  """
  Use RSSParser to get detail
  """
  rel = {}
  rssParser = RSSParser(link)
  rel = rssParser.getDTO().entries
  # Write summary and content to sepetare file for later include
  for entry in rel:
    f = open('app/templates/tmp/'+entry.id[7:].replace('/','_'),'w')
    # Content or Description(summary)
    try:
      content = entry.content[0].value.encode('utf-8')
    except:
      content = entry.description.encode('utf-8')
    f.write(content)
    f.close()
  return rel

def deleteFeed(feedName):
  """
  Delete feed into DB
  """
  # Find target feed but not delete, just delete relation between feed and user in feedUser
  targetFeed = Feed.query.filter_by(name = feedName).first()
  deleteFeedUser = FeedUser.query.filter_by(fid = targetFeed.getId(), uid = g.user.id).first()
  db.session.delete(deleteFeedUser)
  db.session.commit()

def insertStar(feedLink, entryId, action):
  """
  Insert or delete from DB that user starred/unstarred entryID in feed of feedLink
  """
  targetFeed = Feed.query.filter_by(link = feedLink).first()
  # if feed exist with this feedLink
  if not not targetFeed:
    # action = True: insert, action = False: delete
    if action:
      # check if exists
      exists = Star.query.filter_by(fid = targetFeed.getId(), uid = g.user.id, entryid = entryId).first()
      if not exists:
        star = Star(g.user.id, targetFeed.getId(), entryId)
        db.session.add(star)
    else:
      # check if exists
      exists = Star.query.filter_by(fid = targetFeed.getId(), uid = g.user.id, entryid = entryId).first()
      if not not exists:
        star = Star.query.filter_by(fid = targetFeed.getId(), uid = g.user.id, entryid = entryId).first()
        db.session.delete(star)
    db.session.commit()

def createStarredAry(feedLink):
  """
  Use RSSParser to get detail
  """
  rel = []
  targetFeed = Feed.query.filter_by(link = feedLink).first()
  starredEntries = Star.query.filter_by(fid = targetFeed.getId(), uid = g.user.id).all()
  for star in starredEntries:
    rel.append(star.entryid.encode('utf-8'))
  return rel

def findStarred(uid):
  """
  Return a dictionary, key = feed name, value = entry obejct (member of feedparser.entries[])
  """
  rel = {}
  starred = Star.query.filter_by(uid = uid).all()
  for entry in starred:
    entryId = entry.getEntryId()
    feed = Feed.query.filter_by(id = entry.getFeed()).first()
    # get feed name and link
    feedName = feed.getName()
    feedLink = feed.getLink()
    # find what entry have the entryId equal to entryId from DB
    rssParser = RSSParser(feedLink)
    for e in rssParser.getDTO().entries:
      if e.id == entryId:
        rel.setdefault(feedName, []).append(e)
  return rel

def findExplore():
  """
  Return a dictionary, key = feed name, value = entry obejct (member of feedparser.entries[])
  """
  rel = collections.defaultdict(dict)
  starred = Star.query.all()
  for entry in starred:
    fan = User.query.filter_by(id=entry.getUser()).first()
    entryId = entry.getEntryId()
    feed = Feed.query.filter_by(id = entry.getFeed()).first()
    # get feed name and link
    feedName = feed.getName()
    feedLink = feed.getLink()
    # find what entry have the entryId equal to entryId from DB
    starredUser = Star.query.filter_by(entryid=entryId).all()
    for su in starredUser:
      fan = User.query.filter_by(id=su.getUser()).first()
      rel[feedName].setdefault(entryId,[]).append(fan)

  for k,v in rel.iteritems():
    for cur_entryId in v:
      cur_feed = Feed.query.filter_by(name = k).first()
      rssParser = RSSParser(cur_feed.getLink())
      for e in rssParser.getDTO().entries:
        if e.id == cur_entryId:
          v[e]=list(set(v[cur_entryId]))
          del v[cur_entryId]

  return rel

def r_order(exploreEntries):
  order=[]
  for feedName, entries in exploreEntries.iteritems():
    for entry in entries.keys():
      order.append(len(entries[entry]))

  rel=list(set(order))
  rel.sort(reverse=True)
  return rel

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash

from app import db
from app.users.forms import RegisterForm, LoginForm
from app.users.models import User
from app.users.decorators import requires_login

mod = Blueprint('users', __name__, url_prefix='/users')


@mod.route('/me/')
@requires_login
def home():
  return render_template("users/profile.html", user=g.user)

   
@mod.route('/login/', methods=['GET', 'POST'])
def login():
  """
  Login form
  """
  form = LoginForm(request.form)
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and check_password_hash(user.password, form.password.data):
      session['user_id'] = user.id
      flash('Welcome %s' % user.name)
      return redirect(url_for('feed.home'))
    flash('Wrong email or password', 'error-message')
  return render_template("users/login.html", form=form)


@mod.route('/register/', methods=['GET', 'POST'])
def register():
  """
  Registration Form
  """
  form = RegisterForm(request.form)
  if form.validate_on_submit():
    user = User(form.name.data, form.email.data, \
      generate_password_hash(form.password.data),form.gender.data)
    db.session.add(user)
    db.session.commit()

    session['user_id'] = user.id

    flash('Thanks for registering')
    return redirect(url_for('feed.home'))
  return render_template("users/register.html", form=form)


@mod.route('/logout/')
def logout():
  session.pop('user_id', None)
  flash('You were logged out')
  return redirect(url_for('users.login'))

app/templates/feed/detail.html
<!doctype html>
{% extends "base.html" %}

{% block metanav %}
  <a href="{{ url_for('feed.home') }}">Feed Home</a>
  &nbsp; 
  <a href="{{ url_for('users.home') }}">Profile</a>
  &nbsp; 
  <a href="{{ url_for('users.logout') }}">Logout</a>
{% endblock %}


{% block content %}
{% from "forms/macros.html" import render_field %}
<br>
<br>
<br>
<!-- Modal -->
<form class="form-horizontal" method="POST" action="." class="form">
  <div id="subcribeModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="subModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
      <h3 id="subModalLabel">Subribe a RSS </h3>
    </div>
    <div class="modal-body">
      <br>
      <br>
      <fieldset>
        {{ form.csrf_token }}
        {{ render_field(form.link, class="input-xlarge") }}
      </fieldset>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <button type="submit" class="btn btn-custom-lighten">Save RSS</button>
    </div>
  </div>
</form>


<div class="row-fluid">
  <!-- Subcribe button -->
  <div id="subcribe" class="span3" style="text-align:center">
    <button class="btn btn-custom-lighten btn-large" data-toggle="modal" data-target="#subcribeModal" >Subcribe</button>
    <br>
    <br>
    <br>
    <br>
    <div class="left-menu span7 offset2">
      <ul class="nav nav-list bs-docs-sidenav">
        <li class="menu-item"><a href="{{ url_for('feed.home') }}"><i class="icon-home "></i> Home</a></li>
        <li class="menu-item"><a href="{{ url_for('feed.starred') }}"><i class="icon-star"></i> Star</a></li>
        <li class="menu-item"><a href="{{ url_for('feed.explore') }}"><i class="icon-th"></i> Trend</a></li>
        <br>
        {% for entry in entriesAry %}
        <li class="menu-item"><a href="#hero-{{entriesAry.index(entry)}}"><i class="icon-forward"></i> {{entry.title[:5]+'...'}}</a></li>
        {% endfor %}
      </ul>
    </div>
    <br>
    <br>
    <br>
    <br>
  </div>

  <!-- Entries Array -->
  <div id="entries_array" class="span8">
    {% for entry in entriesAry %}
    <div class="hero-unit" id="hero-{{entriesAry.index(entry)}}">
      <div class="media">
        <div class="media-body">
          <h4 class="headline">
            <!-- Title -->
            <a href="{{entry.link}}" target="_blank">{{entry.title}}</a>
          </h4>
          <!-- Author + Published date -->
          <p>by {{entry.author}} at {{entry.published}}</p>

          <!-- Summary or Detail here -->

          <ul class="nav nav-tabs" id="contentSwitch">
            <li class="active"><a href="#summary_{{entriesAry.index(entry)}}" data-toggle="tab">Summary</a></li>
            <li><a href="#full_content_{{entriesAry.index(entry)}}" data-toggle="tab">Content</a></li>
            {% if entry.id in starredAry %}
            <li><a href="{{ url_for('feed.star', entryId=entry.id, feedLink=entry.summary_detail.base, action='del')}}" rel="star" data-placement="right" data-toggle="tooltip" data-original-title="Unstar this entry"><i class="icon-star "></i></a></li>
            {% else %}
            <li><a href="{{ url_for('feed.star', entryId=entry.id, feedLink=entry.summary_detail.base, action='add')}}" rel="star" data-placement="right" data-toggle="tooltip" data-original-title="Star this entry"><i class="icon-star-empty "></i></a></li>
            {% endif %}
          </ul>
       
          <div class="tab-content">
            <div class="tab-pane fade active in" id="summary_{{entriesAry.index(entry)}}">
              {% include 'tmp/sum_'+entry.id[7:].replace('/','_') ignore missing %}
            </div>
            <div class="tab-pane fade in" id="full_content_{{entriesAry.index(entry)}}">
              {% include 'tmp/'+entry.id[7:].replace('/','_') ignore missing %}
            </div>
          </div> 
            
        </div>
      </div>
    </div>
    {% endfor %}
    <br>
    <br>
  </div>
</div>
  

{% endblock %}

app/templates/feed/explore.html
<!doctype html>
{% extends "base.html" %}

{% block metanav %}
  <a href="{{ url_for('feed.home') }}">Feed Home</a>
  &nbsp; 
  <a href="{{ url_for('users.home') }}">Profile</a>
  &nbsp; 
  <a href="{{ url_for('users.logout') }}">Logout</a>
{% endblock %}


{% block content %}
{% from "forms/macros.html" import render_field %}
<br>
<br>
<br>
<!-- Modal -->
<form class="form-horizontal" method="POST" action="." class="form">
  <div id="subcribeModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="subModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
      <h3 id="subModalLabel">Subribe a RSS </h3>
    </div>
    <div class="modal-body">
      <br>
      <br>
      <fieldset>
        {{ form.csrf_token }}
        {{ render_field(form.link, class="input-xlarge") }}
      </fieldset>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <button type="submit" class="btn btn-custom-lighten">Save RSS</button>
    </div>
  </div>
</form>


<div class="row-fluid">
  <!-- Subcribe button -->
  <div id="subcribe" class="span3" style="text-align:center">
    <button class="btn btn-custom-lighten btn-large" data-toggle="modal" data-target="#subcribeModal" >Subcribe</button>
    <br>
    <br>
    <br>
    <br>
    <div class="left-menu span7 offset2">
      <ul class="nav nav-list bs-docs-sidenav">
        <li class="menu-item"><a href="{{ url_for('feed.home') }}"><i class="icon-home "></i> Home</a></li>
        <li class="menu-item"><a href="{{ url_for('feed.starred') }}"><i class="icon-star"></i> Star</a></li>
        <li class="menu-item"><a href="{{ url_for('feed.explore') }}"><i class="icon-th"></i> Trend</a></li>
        <br>
        {% for feedName,entries in exploreEntries.iteritems() %}
          {% for entry in entries.keys() %}
          <li class="menu-item"><a href="#hero-{{exploreEntries.keys().index(feedName)}}-{{entries.keys().index(entry)}}"><i class="icon-forward"></i> {{entry.title[:5]+'...'}}</a></li>
          {% endfor %}
        {% endfor %}
      </ul>
    </div>
    <br>
    <br>
    <br>
    <br>
  </div>

  <!-- Entries Array -->
  <div id="entries_array" class="span8">
    {% for order in ranking_order %}
    
      {% for feedName,entries in exploreEntries.iteritems() %}
        <!-- -->
        {% for entry in entries.keys() %}
          {% if entries[entry]|length == order %}
          <div class="hero-unit" id="hero-{{exploreEntries.keys().index(feedName)}}-{{entries.keys().index(entry)}}">
            <div class="media">
              <div class="media-body">
                <h4 class="headline">
                  <!-- Title -->
                  <a href="{{entry.link}}" target="_blank">{{entry.title}}</a>
                </h4>
                <!-- Author + Published date -->
                <p>by {{entry.author}} at {{entry.published}}
                <br>
                starred by 
                {% for fan in entries[entry] %}
                @{{fan.name}} &nbsp;
                {% endfor %}</p>
                <!-- Summary or Detail here -->
      
                <ul class="nav nav-tabs" id="contentSwitch">
                  <li class="active"><a href="#summary_{{exploreEntries.keys().index(feedName)}}_{{entries.keys().index(entry)}}" data-toggle="tab">Summary</a></li>
                  <li><a href="#full_content_{{exploreEntries.keys().index(feedName)}}_{{entries.keys().index(entry)}}" data-toggle="tab">Content</a></li>
                </ul>
             
                <div class="tab-content">
                  <div class="tab-pane fade active in" id="summary_{{exploreEntries.keys().index(feedName)}}_{{entries.keys().index(entry)}}">
                    {% include 'tmp/sum_'+entry.id[7:].replace('/','_') ignore missing %}
                  </div>
                  <div class="tab-pane fade in" id="full_content_{{exploreEntries.keys().index(feedName)}}_{{entries.keys().index(entry)}}">
                    {% include 'tmp/'+entry.id[7:].replace('/','_') ignore missing %}
                  </div>
                </div> 
                  
              </div>
            </div>
          </div>
          {% endif %}
        {% endfor %}
      {% endfor %}
    {% endfor %}
    <br>
    <br>
  </div>
</div>
  

{% endblock %}

app/templates/feed/home.html
<!doctype html>
{% extends "base.html" %}

{% block metanav %}
  <a href="{{ url_for('users.home') }}">Profile</a>
  &nbsp; 
  <a href="{{ url_for('users.logout') }}">Logout</a>
{% endblock %}


{% block content %}
{% from "forms/macros.html" import render_field %}
<br>
<br>
<br>
 
<!-- Subcribe Modal -->
<form class="form-horizontal" method="POST" action="." class="form">
  <div id="subcribeModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="subModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
      <h3 id="subModalLabel">Subribe a RSS </h3>
    </div>
    <div class="modal-body">
      <br>
      <br>
      <fieldset>
        {{ rform.csrf_token }}
        {{ render_field(rform.link, class="input-xlarge") }}
      </fieldset>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <button type="submit" class="btn btn-custom-lighten">Save RSS</button>
    </div>
  </div>
</form>

<!-- Unsubcribe Modal -->
<form class="form-horizontal" method="POST" action="." class="form">
  <div id="unsubcribeModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="subModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
      <h3 id="subModalLabel">Unsubribe a RSS </h3>
    </div>
    <div class="modal-body">
      <p id="unsubcribe_confirm"></p>
      <div id="hidden-feedName">
        <fieldset>
          {{ dform.csrf_token }}
          {{ render_field(dform.feedName, id="feedName") }}
        </fieldset>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Nope</button>
      <button type="submit" class="btn btn-info">Unsubcribe</button>
    </div>
  </div>
</form>

<div class="row-fluid">
  <!-- Subcribe button -->
  <div id="subcribe" class="span3" style="text-align:center">
    <button class="btn btn-custom-lighten btn-large" data-toggle="modal" data-target="#subcribeModal" >Subcribe</button>
    <div class="left-menu span7 offset2">
      <br>
      <br>
      <br>
      <br>
      <ul class="nav nav-list bs-docs-sidenav">
        <li class="menu-item"><a href="{{ url_for('feed.home') }}"><i class="icon-home"></i> Home</a></li>
        <li class="menu-item"><a href="{{ url_for('feed.starred') }}"><i class="icon-star"></i> Star</a></li>
        <li class="menu-item"><a href="{{ url_for('feed.explore') }}"><i class="icon-th"></i> Trend</a></li>
        <br>
        {% for name,headline in feeds.iteritems()%}
        <li class="menu-item"><a href="{{ url_for('feed.detail', feedName=name, feedLink=headline["link"] )}}"> {{name}} ({{headline["number"]}})</a></li>
        {% endfor %}
      </ul>
      <br>
      <br>
      <br>
      <br>
    </div>
  </div>

  <!-- Feed Table-->
  <div id="feed_table" class="span8">
    {% for name,headline in feeds.iteritems()%}
    <div class="hero-unit">
      <div class="hero-close">
        <button type="button" data-id="{{name}}" class="close unsubcribe" data-toggle="modal" data-target="#unsubcribeModal" rel="star" data-placement="top" data-original-title="Unsubcribe this RSS" >&times;</button>
      </div>
      <div class="media">
        <div class="media-body">
          <h4 class="headline">
            <!-- Title + Number -->
            <a href="{{headline["href"]}}" target="_blank"> {{name}} ({{headline["number"]}})</a>
            </h4>
          <br>
          <!-- Head -->
          <a href="{{ url_for('feed.detail', feedName=name, feedLink=headline["link"] )}}"><p class= "title">{{headline["head"]}}</p></a>
          <!-- Summary-->
          {% include 'tmp/sum_'+headline["entryLink"][7:].replace('/','_') ignore missing %}
        </div>
      </div>
    </div>
    {% endfor %}
    <br>
    <br>
  </div>
</div>

{% endblock %}